import sys
from pathlib import Path
from typing import Final, TypedDict, TypeAlias

if sys.version_info >= (3, 11):
    from typing import NotRequired
    import tomllib
else:
    from typing_extensions import NotRequired
    import tomli as tomllib


TAB: Final = " " * 4
METAFILE_PATH: Final = Path(__file__).parent / "meta.toml"
GEN_FOLDER: Final = Path(__file__).parent / "_generated"
SYMBOLS_PATH: Final = Path(__file__).parent / "_symbols.py"
INIT_TEMPLATE: Final = Path(__file__).parent / "__init__.py.template"
INIT_PATH: Final = Path(__file__).parent / "__init__.py"
UNION_SYMBOL: Final = "Char"


class BMPBlock(TypedDict):
    symbol: str
    promote: NotRequired[list[int]]
    range_start: int
    range_end: int


BMPToml: TypeAlias = dict[str, BMPBlock]


def create_symbol_file(
    name: str,
    symbol: str,
    *,
    range_start: int,
    range_end: int,
    promote: list[int] | None = None,
) -> None:
    GEN_FOLDER.mkdir(parents=True, exist_ok=True)
    dest = GEN_FOLDER / f"{name}.py"

    with dest.open("w", encoding="utf-8") as file:
        file.writelines(
            "\n".join(
                [
                    "# Auto generated by `generate-blocks` script",
                    "",
                    "from typing import TypeAlias, Literal",
                    "",
                    "",
                    f"{symbol}: TypeAlias = Literal[",
                ]
            )
        )

        if promote is not None:
            for promoted_codepoint in promote:
                file.write(repr(chr(promoted_codepoint)))
                file.write(",")

        # NOTE: Missing protection for edge case:
        #     - When there is more codepoints to promote than
        #       the count of codepoints in the range
        for codepoint in range(range_start + 1, range_end + 1):
            if promote is not None and codepoint in promote:
                continue
            file.write(repr(chr(codepoint)))
            if codepoint == range_end:
                break
            file.write(",")

        file.write("]\n")


def load_toml() -> BMPToml:
    with METAFILE_PATH.open("rb") as file:
        toml: dict[str, BMPBlock] = tomllib.load(file)
    return toml


def generate_symbol_layer(toml: BMPToml) -> None:
    char_union = " | ".join(block["symbol"] for block in toml.values())
    with SYMBOLS_PATH.open("w", encoding="utf-8") as file:
        file.writelines(
            "\n".join(
                [
                    "# Auto generated by `generate-symbols` script",
                    "",
                    "from typing import TYPE_CHECKING, TypeAlias",
                    "",
                    "",
                    "if TYPE_CHECKING:",
                    *(
                        f"{TAB}from .{GEN_FOLDER.stem}.{block_name} import {block['symbol']}"
                        for block_name, block in toml.items()
                    ),
                    f"{TAB}{UNION_SYMBOL}: TypeAlias = {char_union}",
                    "else:",
                    f"{TAB}{UNION_SYMBOL} = None",
                    *(f"{TAB}{block['symbol']} = None" for block in toml.values()),
                ]
            )
        )


def generate_init_file(toml: BMPToml) -> None:
    init_template = INIT_TEMPLATE.read_text(encoding="utf-8")
    init_source = init_template.format(
        listed_symbols="\n".join(f"- `{block['symbol']}`" for block in toml.values()),
        quoted_symbols="\n".join(
            f'{TAB}"{block["symbol"]}",' for block in toml.values()
        ),
        imported_symbols="\n".join(
            (
                f"from .{SYMBOLS_PATH.stem} import {UNION_SYMBOL}",
                *(
                    f"from .{SYMBOLS_PATH.stem} import {block['symbol']}"
                    for block in toml.values()
                ),
            )
        ),
    )
    INIT_PATH.write_text(init_source)


def generate_blocks(toml: BMPToml) -> None:
    for block_name, block in toml.items():
        create_symbol_file(
            name=block_name,
            promote=block.get("promote", None),
            symbol=block["symbol"],
            range_start=block["range_start"],
            range_end=block["range_end"],
        )


def generate_all() -> None:
    toml = load_toml()
    generate_init_file(toml)
    generate_symbol_layer(toml)
    generate_blocks(toml)
