# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


ArabicSupplementChar: TypeAlias = Literal['ݑ','ݒ','ݓ','ݔ','ݕ','ݖ','ݗ','ݘ','ݙ','ݚ','ݛ','ݜ','ݝ','ݞ','ݟ','ݠ','ݡ','ݢ','ݣ','ݤ','ݥ','ݦ','ݧ','ݨ','ݩ','ݪ','ݫ','ݬ','ݭ','ݮ','ݯ','ݰ','ݱ','ݲ','ݳ','ݴ','ݵ','ݶ','ݷ','ݸ','ݹ','ݺ','ݻ','ݼ','ݽ','ݾ','ݿ']
