# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


ASCIIChar: TypeAlias = Literal['A','a','1','"','#','$','%','&',"'",'(',')','*','+',',','-','.','/','0','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_']
