# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


BlockElementChar: TypeAlias = Literal['▁','▂','▃','▄','▅','▆','▇','█','▉','▊','▋','▌','▍','▎','▏','▐','░','▒','▓','▔','▕','▖','▗','▘','▙','▚','▛','▜','▝','▞','▟']
