# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


BuhidChar: TypeAlias = Literal['ᝁ','ᝂ','ᝃ','ᝄ','ᝅ','ᝆ','ᝇ','ᝈ','ᝉ','ᝊ','ᝋ','ᝌ','ᝍ','ᝎ','ᝏ','ᝐ','ᝑ','ᝒ','ᝓ','\u1754','\u1755','\u1756','\u1757','\u1758','\u1759','\u175a','\u175b','\u175c','\u175d','\u175e','\u175f']
