# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


CurrencySymbolChar: TypeAlias = Literal['₡','₢','₣','₤','₥','₦','₧','₨','₩','₪','₫','€','₭','₮','₯','₰','₱','₲','₳','₴','₵','₶','₷','₸','₹','₺','₻','₼','₽','₾','₿','⃀','\u20c1','\u20c2','\u20c3','\u20c4','\u20c5','\u20c6','\u20c7','\u20c8','\u20c9','\u20ca','\u20cb','\u20cc','\u20cd','\u20ce','\u20cf']
