# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


CyrillicSupplementChar: TypeAlias = Literal['ԁ','Ԃ','ԃ','Ԅ','ԅ','Ԇ','ԇ','Ԉ','ԉ','Ԋ','ԋ','Ԍ','ԍ','Ԏ','ԏ','Ԑ','ԑ','Ԓ','ԓ','Ԕ','ԕ','Ԗ','ԗ','Ԙ','ԙ','Ԛ','ԛ','Ԝ','ԝ','Ԟ','ԟ','Ԡ','ԡ','Ԣ','ԣ','Ԥ','ԥ','Ԧ','ԧ','Ԩ','ԩ','Ԫ','ԫ','Ԭ','ԭ','Ԯ','ԯ']
