# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


HanunooChar: TypeAlias = Literal['ᜡ','ᜢ','ᜣ','ᜤ','ᜥ','ᜦ','ᜧ','ᜨ','ᜩ','ᜪ','ᜫ','ᜬ','ᜭ','ᜮ','ᜯ','ᜰ','ᜱ','ᜲ','ᜳ','᜴','᜵','᜶','\u1737','\u1738','\u1739','\u173a','\u173b','\u173c','\u173d','\u173e','\u173f']
