# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


SuperscriptAndSubscriptChar: TypeAlias = Literal['ⁱ','\u2072','\u2073','⁴','⁵','⁶','⁷','⁸','⁹','⁺','⁻','⁼','⁽','⁾','ⁿ','₀','₁','₂','₃','₄','₅','₆','₇','₈','₉','₊','₋','₌','₍','₎','\u208f','ₐ','ₑ','ₒ','ₓ','ₔ','ₕ','ₖ','ₗ','ₘ','ₙ','ₚ','ₛ','ₜ','\u209d','\u209e','\u209f']
