# Auto generated by `generate-blocks` script

from typing import TypeAlias, Literal


TagalogChar: TypeAlias = Literal['ᜁ','ᜂ','ᜃ','ᜄ','ᜅ','ᜆ','ᜇ','ᜈ','ᜉ','ᜊ','ᜋ','ᜌ','ᜍ','ᜎ','ᜏ','ᜐ','ᜑ','ᜒ','ᜓ','᜔','᜕','\u1716','\u1717','\u1718','\u1719','\u171a','\u171b','\u171c','\u171d','\u171e','ᜟ']
